title: "nix.ug"
subtitle: "Nix/NixOS User Group Directory"
logo: "logo.svg"

header: true
footer: '<p>Created with <span class="has-text-danger">❄️</span> using <a href="https://github.com/bastienwirtz/homer">Homer</a> and <a href="https://nixos.org/">Nix</a></i></a></p>'

theme: default
colors:
  light:
    highlight-primary: "#5277c3"
    highlight-secondary: "#5277c3"
    highlight-hover: "#7eb9e3"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#5277c3"
    highlight-secondary: "#5277c3"
    highlight-hover: "#7eb9e3"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

message:
  style: "is-dark"
  title: "What is a NUG?"
  icon: "fa fa-snowflake"
  content: "A Nix User Group (NUG) is a place where you can go to hang out with friends to learn about and use Nix. Typically this includes physical in-person meetups that happen regularly, though we catalogue online events too!"

links:
  - name: "Add a new NUG to this list"
    icon: "fas fa-square-plus"
    url: "https://github.com/nix-how/nix.ug#adding-a-new-user-group-or-event-to-the-list"
  - name: "Receive event funding"
    icon: "fas fa-dollar-sign"
    url: "https://nixos.org/community/event-funding.html"

defaults:
  layout: list
  colorTheme: auto

services:
- items:
  - keywords: ''
    logo: assets/nix.camp/logo.png
    name: Nix.Camp
    subtitle: Yearly, often in Wales
    tag: United Kingdom/Wales
    target: _blank
    url: https://nix.camp/
  - keywords: ''
    logo: assets/nix.party/logo.png
    name: Nix.Party
    subtitle: Celebrating 20 years of Nix
    tag: Wherever
    target: _blank
    url: https://www.nix.party/
  - keywords: ''
    logo: assets/nixcon/logo.png
    name: NixCon
    subtitle: Yearly, Europe
    tag: Europe
    target: _blank
    url: https://2023.nixcon.org/
  name: Events
- items:
  - icon: ''
    keywords: online offline
    logo: assets/aalborg/logo.svg
    name: Nix Aalborg Community
    subtitle: No strict schedule
    tag: Denmark
    target: _blank
    url: https://matrix.to/#/#nix-aalborg:rend.al
  - icon: fas fa-snowflake
    keywords: offline in-person aalen germany
    logo: ''
    name: Aalen NixOS Meetup
    subtitle: Every first Tuesday
    tag: Germany
    target: _blank
    url: https://matrix.to/#/#nixos-aalen:matrix.org
  - icon: ''
    keywords: offline online in-person austria österreich graz vienna
    logo: assets/austria/logo.svg
    name: NixOS User Group Austria
    subtitle: No strict schedule
    tag: Austria
    target: _blank
    url: https://nixos.at
  - icon: fas fa-snowflake
    keywords: online offline
    logo: ''
    name: Berlin NixOS Meetup
    subtitle: Thursdays Online, Tuesdays Offline
    tag: Germany
    target: _blank
    url: https://www.meetup.com/Berlin-NixOS-Meetup/
  - icon: ''
    keywords: offline in-person bochum germany
    logo: assets/bochum/logo.svg
    name: Nix Learning Group Bochum
    subtitle: Monthly, beginner-friendly meetup
    tag: Germany
    target: _blank
    url: https://github.com/nix-community-bochum/nix-learning-group
  - icon: ''
    keywords: København Roskilde Malmö Lund Sjælland Skåne
    logo: assets/copenhagen/logo.png
    name: Greater Copenhagen NixOS User Group
    subtitle: 4 times a year
    tag: Denmark
    target: _blank
    url: https://www.meetup.com/greater-copenhagen-nixos-user-group/
  - icon: ''
    keywords: Meetup
    logo: assets/dresden/logo.svg
    name: nix-meetup | Dresden
    subtitle: about once a month
    tag: Germany
    target: _blank
    url: https://c3d2.de/nix-meetup.html
  - icon: ''
    keywords: online
    logo: assets/grenug/logo.svg
    name: Grenoble Nix User Group
    subtitle: No strict schedule
    tag: France
    target: _blank
    url: https://grenug.fr/
  - icon: ''
    keywords: offline hamburg germany
    logo: assets/hamburg/logo.svg
    name: Nix Hamburg User Group
    subtitle: Biweekly meeting on thursday
    tag: Germany
    target: _blank
    url: https://nix-hh.de/
  - icon: fas fa-snowflake
    logo: ''
    name: Nix/NixOS Israel User Group
    subtitle: No strict schedule
    tag: Israel
    target: _blank
    url: https://israel.nix.ug
  - icon: fas fa-snowflake
    keywords: online
    logo: ''
    name: Nix Italia
    subtitle: No strict schedule
    tag: Italy
    target: _blank
    url: https://matrix.to/#/#it:nixos.org
  - icon: ''
    keywords: offline
    logo: assets/livnug/logo.svg
    name: Liverpool Nix User Group (LivNUG)
    subtitle: The first Thursday of each month at 7pm GMT
    tag: United Kingdom
    target: _blank
    url: https://liverpool.nix.ug
  - icon: fas fa-snowflake
    keywords: offline
    logo: ''
    name: London Nix User Group
    subtitle: About once every two months
    tag: United Kingdom
    url: https://www.eventbrite.co.uk/e/london-nix-user-group-tickets-729795787847
  - icon: fas fa-snowflake
    keywords: offline in-person
    logo: ''
    name: Madrid Nix / NixOS User Group
    subtitle: No strict schedule
    tag: Spain
    target: _blank
    url: https://www.meetup.com/madrid-nix-nixos-user-group
  - icon: fas fa-snowflake
    keywords: online offline
    logo: ''
    name: New York Nix Users Group
    subtitle: No strict schedule
    tag: NewYork
    target: _blank
    url: https://www.meetup.com/new-york-nix-users-group/
  - icon: fas fa-snowflake
    keywords: ''
    logo: ''
    name: Nix Netherlands
    subtitle: No strict schedule
    tag: Netherlands
    target: _blank
    url: https://discourse.nixos.org/t/dutch-nix-meetup/26599
  - icon: fas fa-snowflake
    keywords: offline in-person nürnberg germany
    logo: ''
    name: Nürnberg NixOS Meetup
    subtitle: Every third Tuesday at Nerdberg e.V.
    tag: Germany
    target: _blank
    url: https://matrix.to/#/#nixos-nuernberg:matrix.org
  - icon: fas fa-snowflake
    keywords: online offline
    logo: ''
    name: Oslo NixOS User Group
    subtitle: Whenever Stig feels like it
    tag: Oslo
    target: _blank
    url: https://www.meetup.com/Oslo-NixOS-User-Group/
  - icon: fas fa-snowflake
    keywords: online in person
    logo: ''
    name: Nixers in Paris
    subtitle: No strict schedule
    tag: France
    target: _blank
    url: https://matrix.to/#/#fr:nixos.org
  - icon: fas fa-snowflake
    keywords: offline in-person california
    logo: ''
    name: Socal Nix Users Group
    subtitle: No strict schedule
    tag: America
    target: _blank
    url: https://socal-nug.com/
  - icon: fas fa-snowflake
    keywords: offline in-person stuttgart germany
    logo: ''
    name: Stuttgart NixOS Meetup
    subtitle: Every second Tuesday at alternating locations
    tag: Germany
    target: _blank
    url: https://matrix.to/#/#nixos-stuttgart:matrix.org
  - icon: fas fa-snowflake
    keywords: self hosted reddit
    logo: ''
    name: Silicon Valley Nix User Group
    subtitle: No strict schedule
    tag: America
    target: _blank
    url: https://www.svnix.com/
  - icon: fas fa-snowflake
    keywords: thailand chiang mai chiangmai nix nixos open source foss linux infrastructure
      as code
    logo: ''
    name: NixOS Thailand
    subtitle: Regular Meetups in Thailand
    tag: Thailand
    target: _blank
    url: https://matrix.to/#/#nixos-thailand:matrix.org
  - icon: ''
    keywords: offline in-person
    logo: assets/zurich/logo.png
    name: NixOS User Group Zürich
    subtitle: No strict schedule
    tag: Switzerland
    target: _blank
    url: https://www.meetup.com/NixOS-User-Group-Zurich/
  name: NUGs
